### ISSUE TITLE
Error 500 with PHP 8.1/8.2

### ISSUE THREAD

**Issue by mcnesium** [simpleid/simpleid#87]
### Description

SimpleID v1.0.4 throws a 500, when run with PHP 8.1 or 8.2 (not 8.0!)

### Logs

    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "[12-Mar-2023 13:39:42 Europe/Berlin] PHP Fatal error:  Uncaught Error: reset(): Argument #1 ($array) cannot be passed by reference in /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php:909"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "Stack trace:"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#0 /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php(435): XTemplate->scan_globals()"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#1 /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php(397): XTemplate->setup()"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#2 /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php(320): XTemplate->restart('html/template.x...', '', NULL, 'main', true, '{', '}')"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#3 /…/simpleid-release-1.0.4/www/index.php(113): XTemplate->__construct('html/template.x...')"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#4 /…/simpleid-release-1.0.4/www/index.php(101): simpleid_start()"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#5 {main}"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "  thrown in /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php on line 909"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "[12-Mar-2023 13:39:42 Europe/Berlin] PHP Fatal error:  Uncaught Error: reset(): Argument #1 ($array) cannot be passed by reference in /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php:909"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "Stack trace:"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#0 /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php(435): XTemplate->scan_globals()"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#1 /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php(397): XTemplate->setup()"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#2 /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php(320): XTemplate->restart('html/template.x...', '', NULL, 'main', true, '{', '}')"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#3 /…/simpleid-release-1.0.4/www/index.php(113): XTemplate->__construct('html/template.x...')"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#4 /…/simpleid-release-1.0.4/www/index.php(101): simpleid_start()"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "#5 {main}"
    [12-Mar-2023 13:39:42] WARNING: [pool www] child 24316 said into stderr: "  thrown in /…/simpleid-release-1.0.4/www/lib/xtemplate.class.php on line 909"

**Comment by kelvinmo** [comment]
This should be fixed with PR #85

**Comment by mcnesium** [comment]
Approved. Thank you very much for still supporting this :+1:
